# Generated by Django 5.2.1 on 2025-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('imdb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date', models.CharField(max_length=4)),
                ('sposter', models.ImageField(upload_to='media_posters/')),
                ('bposter', models.ImageField(upload_to='media_posters/')),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('trailer', models.FileField(upload_to='media_trailers/')),
                ('medium', models.FileField(upload_to='media_files/')),
            ],
        ),
    ]
